main: pl.sadboifilip.mcapi.App
name: MinecraftAPI
description: Simple API for minecraft spigot servers to allow users some actions based on their server role.
version: 1.0

commands:
    "mcapi-token":
        description: Get your token for rest api requests
        usage: /mcapi-token
    "mcapi-start":
        description: Starts rest server on provided port. If port was not provided it will take 7000 by default
        usage: /mcapi-start 7000
    "mcapi-stop":
        description: Stops started server
        usage: /mcapi-stop
